version: 2.1

jobs:
  deploy-prod:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          command: apk add ruby-dev
          background: true
      - run: 
          command: apk add git 
          background: true
      - run: 
          command: apk add curl
          background: true
      - run: 
          command: gem install dpl
          background: true
      - run: 
          command: gem install json_pure
          background: true
      - run:
          command: |
            cd src
            dpl --provider=heroku --app=$HEROKU_APP_PROD --api-key=$HEROKU_APIKEY
          when: on_success

workflows:
  deploy:
    jobs:
      - deploy-prod