version: 2.1

jobs:
  deploy-prod:
    docker:
      - image: alpine
    steps:
      - checkout
      - run: apk add ruby-dev
      - run: apk add git 
      - run: apk add curl
      - run: gem install dpl
      - run: gem install json_pure
      - run:
          command: |
            cd src
            dpl --provider=heroku --app=$HEROKU_APP_PROD --api-key=$HEROKU_APIKEY
          when: on_success

workflows:
  deploy:
    jobs:
      - deploy-prod